---
title: "BTC-Forecast"
author: "JDRK"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE)

library(prettydoc)
library(hrbrthemes)

        
library(stringr)
library(janitor)
library(tidyr)
library(dplyr)
library(formattable)
library(DT)
library(gt)
library(lubridate)
library(quantmod)
library(pacman)
library(scales)
library(data.table)
library(openxlsx)
library(readxl) 
library(tibble)
library(ggplot2)
library(plotly)
library(tseries)
library(forecast)


getSymbols("BTC-USD",from="2015-01-01")

btc<-rownames_to_column(data.frame(`BTC-USD`))


btc<-
btc %>% select(rowname,BTC.USD.Adjusted) %>% 
rename(date=rowname,price=BTC.USD.Adjusted) %>% mutate(date=ymd(date))%>% 
mutate(mn=round_date(date,"month"),wk=round_date(date,"week")) 

#--------------------------------------------------------------------------
mn<-btc %>% group_by(mn) %>% summarize(price=mean(price))

#Last

mnts<-ts(mn$price,start =c(2015,1) ,end =c(2023,7) ,frequency = 12)


autoplot(decompose(diff(mnts)))


mna<-auto.arima(mnts)

mnf<-forecast(mna,h = 13)

autoplot(mnf)

detect_last<-
cbind(rownames_to_column(data.frame(mnf))
,mn[c(104:116),] ) %>% select(mn,Point.Forecast,price,Hi.80,Lo.80,Lo.95,Hi.95) %>% mutate(Hi=(Hi.80+Hi.95)/2,Low=(Lo.80+Lo.95)/2) %>% select(mn,price,Point.Forecast,Hi,Low)


detect_last_gt<-
detect_last %>% gt() %>% fmt_number(columns = c(2:5),decimals = 2) %>% fmt_date(columns = 1,date_style = "yMMM") %>% tab_row_group(label ="2023" ,rows =mn<"2023-12-31" ,id = "2023",group = "2023")%>% tab_row_group(label ="2024" ,rows =mn>="2024-1-1" ,id = "2024",group = "2024") %>% cols_label(mn="Date") %>% cols_label_with(columns = everything(),fn = toupper) %>% summary_rows(groups = everything(),columns = c(2:5),fns = list(AVG=~mean(.)),formatter = fmt_number,decimals=1) %>% row_group_order(groups = c("2023","2024")) %>% tab_header(title = "Forecast Last Year Data") %>% opt_stylize(style = 3) %>% tab_style(style =list(cell_fill(color="#eccc68"),cell_text(color="black",weight = "bold")) ,locations = cells_title()) %>% tab_style(style =list(cell_fill(color="#eccc68"),cell_text(color="black",weight = "bold")) ,locations = cells_summary()) %>% tab_style(style =list(cell_fill(color="black"),cell_text(color="white",weight = "bold")) ,locations = cells_stub_summary())%>% tab_style(style =list(cell_fill(color="#ced6e0"),cell_text(color="black",weight = "bold")) ,locations = cells_group()) %>% tab_style(style =list(cell_text(color="black",weight = "bold",align = "center")) ,locations = cells_body())   
  
  
  
detect_last_chart<-
detect_last %>% mutate(mn=as.POSIXct(mn)) %>% select(mn,price,Point.Forecast,Hi,Low)%>% 
pivot_longer(!mn,names_to = "cat",values_to = "price") %>% 
ggplot(aes(x=mn,y = price,color=cat,group=cat))+geom_line()+
scale_x_datetime(date_breaks ="month" ,date_labels = "%b-%Y")+theme_bw()+
labs(x="",y="")+
scale_y_continuous(breaks = c(5000,15000,25000,35000,45000,55000,65000,75000))+
theme(axis.text.x = element_text(face = "bold",size=10,color="black",angle = 90),
axis.text.y = element_text(face = "bold",size=10,color="black"))


#Real

mrts<-ts(mn$price,start =c(2015,1) ,end =c(2024,8) ,frequency = 12)

mra<-auto.arima(mrts)

mrf<-forecast(mra,h = 12)

autoplot(mrf)

nextf<-data.frame(mn=seq(as.Date("2024-09-1"),by="month",len=12))

mn_add_gt<-
cbind(rownames_to_column(data.frame(mrf)),nextf) %>% 
select(mn,Point.Forecast,Lo.95,Hi.95,Hi.80,Lo.80) %>% mutate(low=(Lo.80+Lo.95)/2,high=(Hi.80+Hi.95)/2) %>% rename(Date=mn)%>%select(Date,Point.Forecast,low,high)%>% gt() %>% fmt_number(columns = c(2:4),decimals = 2) %>% fmt_date(columns = 1,date_style = "yMMM") %>% tab_row_group(label ="2023" ,rows =Date<"2024-12-31" ,id = "2024",group = "2024")%>% tab_row_group(label ="2025" ,rows =Date>="2025-1-1" ,id = "2025",group = "2025")  %>% cols_label_with(columns = everything(),fn = toupper) %>% summary_rows(groups = everything(),columns = c(2:4),fns = list(AVG=~mean(.)),formatter = fmt_number,decimals=1) %>% row_group_order(groups = c("2024","2025")) %>% tab_header(title = "Forecast Next Year") %>% opt_stylize(style = 3) %>% tab_style(style =list(cell_fill(color="#eccc68"),cell_text(color="black",weight = "bold")) ,locations = cells_title()) %>% tab_style(style =list(cell_fill(color="#eccc68"),cell_text(color="black",weight = "bold")) ,locations = cells_summary()) %>% tab_style(style =list(cell_fill(color="black"),cell_text(color="white",weight = "bold")) ,locations = cells_stub_summary())%>% tab_style(style =list(cell_fill(color="#ced6e0"),cell_text(color="black",weight = "bold")) ,locations = cells_group()) %>% tab_style(style =list(cell_text(color="black",weight = "bold",align = "center")) ,locations = cells_body())   
  

  

mn_add_chart<-
cbind(rownames_to_column(data.frame(mrf)),nextf) %>% 
select(mn,Point.Forecast,Lo.95,Hi.95,Hi.80,Lo.80) %>% mutate(low=(Lo.80+Lo.95)/2,high=(Hi.80+Hi.95)/2) %>% rename(Date=mn)%>%select(Date,Point.Forecast,low,high)%>%
pivot_longer(!Date,names_to ="cat" ,values_to = "price") %>% 
mutate(mn=as.POSIXct(Date))%>% filter(Date>"2017-12-31") %>% 
ggplot(aes(x=mn,y=price,color=cat,group=cat))+geom_line(size=0.7)+
scale_fill_brewer(palette = "Set1")+
theme_bw()+
theme(axis.text.x = element_text(angle = 90,color="black",size=10),
axis.text.y = element_text(color="black",size=10),
plot.title = element_text(face = "bold",colour = "brown",size = 15),
plot.subtitle = element_text(face = "bold.italic",colour = "black"))+labs(x="",y="")+
scale_x_datetime(date_breaks ="month" ,date_labels = "%b-%Y")+
scale_y_continuous(breaks =  c(30000,50000,70000,90000))

```


 


### Last_Year


Data Periods From: Jan 2015 To Aug 2023


```{r}
ggplotly( detect_last_chart,width = 900)
```

### Last_Year_TBL
```{r}
detect_last_gt
```

### Next Year Chart

```{r}
ggplotly( mn_add_chart,width = 900)
```

 
### Next Year TBL
```{r}
mn_add_gt
```

 
-----------------------------------------------------------------------------

### Other Models:

[S&P500 Model:](https://afaaqitc.github.io/SP500/#Last_Year_Table)

[Oil-CL=F Model:](https://afaaqitc.github.io/OIL-Forecast/#Detect_Forecast_Model_Fore_Last_8_Months)
 
 
 
  